# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

  name: build
  on: [ push, pull_request ]

  jobs:
    build:
      strategy:
        matrix:
          java: [ 17 ]
      runs-on: ubuntu-latest
      env:
        PUBLISH_SUFFIX: snapshots
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      steps:
        - name: checkout repository
          uses: actions/checkout@v2

        - name: setup jdk ${{ matrix.java }}
          uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}

        - name: make gradle wrapper executable
          run: chmod +x ./gradlew

        - name: build
          run: ./gradlew buildOrPublish

        - name: capture build artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Artifacts
            path: build/libs/